export const areaList = [
  {
    companyName: null,
    region: "330206",
    capacity: null,
    value: 74.16,
    industry: null,
    regionName: "北仑区",
    sort: null,
    companyId: null,
    lat: null,
    lng: null,
  },
  {
    companyName: null,
    region: "330212",
    capacity: null,
    value: 1.64,
    industry: null,
    regionName: "鄞州区",
    sort: null,
    companyId: null,
    lat: null,
    lng: null,
  },
  {
    companyName: null,
    region: "330282",
    capacity: null,
    value: 0.0,
    industry: null,
    regionName: "慈溪市",
    sort: null,
    companyId: null,
    lat: null,
    lng: null,
  },
  {
    companyName: null,
    region: "330283",
    capacity: null,
    value: 0.0,
    industry: null,
    regionName: "奉化市",
    sort: null,
    companyId: null,
    lat: null,
    lng: null,
  },
  {
    companyName: null,
    region: "330281",
    capacity: null,
    value: 0.0,
    industry: null,
    regionName: "余姚市",
    sort: null,
    companyId: null,
    lat: null,
    lng: null,
  },
  {
    companyName: null,
    region: "330203",
    capacity: null,
    value: 0.0,
    industry: null,
    regionName: "海曙区",
    sort: null,
    companyId: null,
    lat: null,
    lng: null,
  },
  {
    companyName: null,
    region: "330225",
    capacity: null,
    value: 0.0,
    industry: null,
    regionName: "象山县",
    sort: null,
    companyId: null,
    lat: null,
    lng: null,
  },
  {
    companyName: null,
    region: "330204",
    capacity: null,
    value: 0.0,
    industry: null,
    regionName: "江东区",
    sort: null,
    companyId: null,
    lat: null,
    lng: null,
  },
  {
    companyName: null,
    region: "330226",
    capacity: null,
    value: 0.0,
    industry: null,
    regionName: "宁海县",
    sort: null,
    companyId: null,
    lat: null,
    lng: null,
  },
  {
    companyName: null,
    region: "330205",
    capacity: null,
    value: 0.0,
    industry: null,
    regionName: "江北区",
    sort: null,
    companyId: null,
    lat: null,
    lng: null,
  },
  {
    companyName: null,
    region: "330211",
    capacity: null,
    value: 0.0,
    industry: null,
    regionName: "镇海区",
    sort: null,
    companyId: null,
    lat: null,
    lng: null,
  },
];

export const companyList = [
  {
      "companyName": "公司1号",
      "region": "330282",
      "capacity": null,
      "value": 0.0,
      "industry": null,
      "regionName": null,
      "sort": null,
      "companyId": "HW_002",
      "lat": "30.340481",
      "lng": "121.352453"
  },
  {
      "companyName": "公司2号",
      "region": "330282",
      "capacity": null,
      "value": 0.0,
      "industry": null,
      "regionName": null,
      "sort": null,
      "companyId": "HW_001",
      "lat": "30.340481",
      "lng": "121.352453"
  },
  {
      "companyName": "公司3号",
      "region": "330206",
      "capacity": null,
      "value": 0.0,
      "industry": null,
      "regionName": null,
      "sort": null,
      "companyId": "001",
      "lat": "29.8608816069014",
      "lng": "121.757827408737"
  },
  {
      "companyName": "公司4号",
      "region": "330211",
      "capacity": null,
      "value": 0.0,
      "industry": null,
      "regionName": null,
      "sort": null,
      "companyId": "41298",
      "lat": "29.9629",
      "lng": "121.5736"
  },
  {
      "companyName": "公司5号",
      "region": "330282",
      "capacity": null,
      "value": 0.0,
      "industry": null,
      "regionName": null,
      "sort": null,
      "companyId": "jkgc_01",
      "lat": "30.348391",
      "lng": "121.275038"
  },
  {
      "companyName": "公司6号",
      "region": "330212",
      "capacity": null,
      "value": 0.0,
      "industry": null,
      "regionName": null,
      "sort": null,
      "companyId": "LG_001",
      "lat": "29.771202",
      "lng": "121.525085"
  },
  {
      "companyName": "公司7号",
      "region": "330200",
      "capacity": null,
      "value": 0.0,
      "industry": null,
      "regionName": null,
      "sort": null,
      "companyId": "728119821",
      "lat": null,
      "lng": null
  }
]

export const regionByCompany = [
  {
      "companyName": "公司1号",
      "region": "330282",
      "capacity": null,
      "value": 0.0,
      "industry": null,
      "regionName": null,
      "sort": null,
      "companyId": "HW_002",
      "lat": "30.340481",
      "lng": "121.352453"
  },
  {
      "companyName": "公司2号",
      "region": "330282",
      "capacity": null,
      "value": 0.0,
      "industry": null,
      "regionName": null,
      "sort": null,
      "companyId": "HW_001",
      "lat": "30.340481",
      "lng": "121.352453"
  },
  {
      "companyName": "公司5号",
      "region": "330282",
      "capacity": null,
      "value": 0.0,
      "industry": null,
      "regionName": null,
      "sort": null,
      "companyId": "jkgc_01",
      "lat": "30.348391",
      "lng": "121.275038"
  }
]
